### ISSUE TITLE
Unable to run due to symlink

### ISSUE THREAD

**Issue by kevin-onx** [PDFTron/webviewer-3d-sample#1]
model-viewer.js -> /Users/kristianhein/Documents/Projects/model-viewer/packages/model-viewer/dist/model-viewer.js.
 
 Issue is because of : https://github.com/PDFTron/webviewer-3d-sample/blob/master/public/model-viewer.js

**Comment by khein-pdftron** [comment]
Hello. Thank you for reporting the issue. I pushed the real file. It should work now.
